### ISSUE TITLE
Spotify is not an Electron app

### ISSUE THREAD

**Issue by sylveon** [WICG/window-controls-overlay#24]
The document mentions that Spotify is an Electron app:
![image](https://user-images.githubusercontent.com/6440374/132900016-b995abde-1d7b-474e-984b-eabbfeddb55e.png)

However, this is not true: Spotify uses CEF, not Electron.

**Comment by amandabaker** [comment]
Thanks for calling this out! To stay on the safe side, I removed the details about the framework that Spotify and the other examples are built on in #26 .

**Comment by dandv** [comment]
For those who land here from a web search:

https://www.spotify.com/us/opensource/

https://github.com/chromiumembedded/cef

**Comment by nyanvil** [comment]
same shit different toilet
