### ISSUE TITLE
Define the concept of a "window controls overlay"

### ISSUE THREAD

**Issue by yoavweiss** [WICG/window-controls-overlay#30]
See https://groups.google.com/a/chromium.org/g/blink-dev/c/guI1QCPJTAA/m/fnNrX7V1BQAJ

**Comment by diekus** [comment]
I've added definition of Window Controls Overlay and Window Controls

**Comment by yoavweiss** [comment]
https://wicg.github.io/window-controls-overlay/#concepts now cover this. Closing
