### ISSUE TITLE
"Update the overlay area information" is not well-defined

### ISSUE THREAD

**Issue by yoavweiss** [WICG/window-controls-overlay#33]
[Update the overlay area information](https://wicg.github.io/window-controls-overlay/#update-the-overlay-area-information) doesn't indicate processing model steps, but says in prose what should happen when. That's not great.

What you want is to define what the "title bar area" is, hook up a resize algorithm for it, and then call this algorithm from there. Then you want this algorithm to be specific:
* The env variables need to be stored on an object (Document or Browsing Context, probably?)
* Then this algorithm needs to change them, and the CSS processing model needs to read them off of this object.

**Comment by yoavweiss** [comment]
https://wicg.github.io/window-controls-overlay/#update-the-overlay-area-information is an improvement.
At the same time, it's not yet clear when this algorithm is called.

**Comment by inexorabletash** [comment]
To be more precise, I think we need a clear path from https://html.spec.whatwg.org/multipage/webappapis.html#event-loop-processing-model (specifically steps 11.7) through https://drafts.csswg.org/cssom-view/#run-the-resize-steps to your steps. You could do this by "monkey patching" the CSSOM-View steps, e.g. add something like this somewhere: _"When asked to run the resize steps for a Document doc, also run these steps. 1. Run the steps to resize the title bar area for doc's window"_

**Comment by inexorabletash** [comment]
Oooops, left a comment on the wrong issue. I think this was further updated, though?

**Comment by diekus** [comment]
@inexorabletash Hola Joshua, yes, I had a meeting with Yoav and ironed out the problems. The new changes, (including the monkey patch to CSSOM) should be live very soon.

**Comment by yoavweiss** [comment]
It's now called from https://wicg.github.io/window-controls-overlay/#dfn-title-bar-region-resizes
Closing.
