### ISSUE TITLE
Add support for Feature kRoundedDisplay

### ISSUE THREAD

**Issue by Depresst0** [WICG/window-controls-overlay#66]
Add Rounded Corners support for the Overlay. This is what happens with WCO on a Rounded Display flag-enabled Chromebook. (the wallpaper is a chrome:// site I found in ChromeOS 121.)
[Screen recording 2024-03-10 12.54.36 PM.webm](https://github.com/WICG/window-controls-overlay/assets/145872196/9ad4cd8d-1228-441c-95bf-42874927592e)
and the problem also exists on other test pages.

**Comment by amandabaker** [comment]
Thanks for the feedback! Since this is specific to Chromium and not general feedback about the API, I opened a bug to track fixing the issue here: https://issues.chromium.org/issues/329011033
